# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26e9b01aea160a60e871a9bec34fffbbed8fc93387c128571c81321c7371e618a85fdaa6fd288d6d513f1700eaf11605ad33f769f56e87f48fb042f7c99c8938

test:
  secret_key_base: 8ccdd9103d32368511e428e7adc312599a23654de82dc6ab44834b835f146d5468b348055c1e3fff428edd827768addc944f1868679eb055790aa5bb5327d0e7

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging_bj:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
